## Travis CI Script (JUST FOR TEST)
# DualBootPatcher build from source (only "apk for debug release" for now)
# Thanks @Rendyindo and @webmaster33

dist: trusty
sudo: required
language: c

before_install:
  ## Save ENV dir
  - cd ../
  - export ENV_DIR=$(pwd)

install:
  # install all necessary dependencies
  - sudo apt install ccache expect libboost-dev libjansson-dev libssl-dev libyaml-cpp-dev openssl python-minimal

  # install updated jansson
  - cd ${ENV_DIR}/
  - wget -q http://www.digip.org/jansson/releases/jansson-2.9.tar.gz
  - tar xzf jansson-2.9.tar.gz
  - cd ${ENV_DIR}/jansson-2.9/
  - ./configure
  - make
  - sudo make install

  # install updated OpenSSL
  - cd ${ENV_DIR}/
  - wget -q https://www.openssl.org/source/openssl-1.1.0c.tar.gz
  - tar xzf openssl-1.1.0c.tar.gz
  - cd ${ENV_DIR}/openssl-1.1.0c
  - ./config shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
  - 2>/dev/null 1>&2 make
  - 2>/dev/null 1>&2 sudo make install
  - export PATH=${PATH}:/usr/local/ssl

  # install latest cmake and compile with OpenSSL
  - cd ${ENV_DIR}/
  - git clone --quiet https://gitlab.kitware.com/cmake/cmake.git cmake
  - cd ${ENV_DIR}/cmake/
  - sed -i 's|cmake_options="-DCMAKE_BOOTSTRAP=1"|cmake_options="-DCMAKE_BOOTSTRAP=1 -DCMAKE_USE_OPENSSL=ON"|' ${ENV_DIR}/cmake/bootstrap
  - ./bootstrap
  - make
  - sudo make install

  # get Android NDK R13b
  - cd ${ENV_DIR}/
  - mkdir -p ${ENV_DIR}/android-ndk
  - cd ${ENV_DIR}/android-ndk
  - wget -q https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -qq android-ndk-r13b-linux-x86_64.zip

  # get SDK R25.2.3
  - cd ${ENV_DIR}/
  - mkdir -p ${ENV_DIR}/android-sdk
  - cd ${ENV_DIR}/android-sdk
  - wget -q https://dl.google.com/android/repository/tools_r25.2.3-linux.zip
  - unzip -qq tools_r25.2.3-linux.zip

  # set the ENV variables
  - export ANDROID_HOME=${ENV_DIR}/android-sdk
  - export ANDROID_NDK_HOME=${ENV_DIR}/android-ndk/android-ndk-r13b
  - export ANDROID_NDK=${ANDROID_NDK_HOME}

  # Update SDK, autoconfirm license questions
  - cd ${ENV_DIR}/
  - expect -c 'spawn android-sdk/tools/android update sdk --no-ui --all; expect "Do you accept the license"; send -- "y\r"; expect eof'

script:
  # build DualBootPatcher! (only "apk for debug release" for now)
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build/
  - cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug
  - make
  - rm -rf assets && cpack -G TXZ
  - make apk

## Deploy DualBootPatcher to transfer.sh (only "apk for debug release" for now)
after_success:
  - export TRAVIS_CURRENT_DATE=$(date +"%d%m%y-%Hh%Mm%Ss")
  - ls -l ${TRAVIS_BUILD_DIR}/build/Android_GUI/build/outputs/apk/Android_GUI-debug.apk
  - md5sum ${TRAVIS_BUILD_DIR}/build/Android_GUI/build/outputs/apk/Android_GUI-debug.apk
  - curl --upload-file ${TRAVIS_BUILD_DIR}/build/Android_GUI/build/outputs/apk/Android_GUI-debug.apk https://transfer.sh/Android_GUI-debug-${TRAVIS_CURRENT_DATE}.apk

