## Travis CI Script (JUST FOR TEST)
# DualBootPatcher build from source (only "apk for debug release" for now)

sudo: required
language: c

before_install:
  ## Save ENV dir
  - cd ../
  - export ENV_DIR=$(pwd)

install:
  # install dependencies
  - sudo apt-get install libjansson-dev
  - sudo apt-get install openssl
  - sudo apt-get install libssl-dev
  - sudo apt-get install libyaml-cpp-dev
  - sudo apt-get install libboost-dev
  - sudo apt-get install ccache
  - sudo apt-get install python-minimal
  - sudo apt-get install expect

  # install cmake 3.6.3, compiled with OPENSSL support!
  - cd ${ENV_DIR}/
  - wget https://cmake.org/files/v3.6/cmake-3.6.3.tar.gz
  - tar xzf cmake-3.6.3.tar.gz
  - cd ${ENV_DIR}/cmake-3.6.3/
  - sudo sed -i 's|cmake_options="-DCMAKE_BOOTSTRAP=1"|cmake_options="-DCMAKE_BOOTSTRAP=1 -DCMAKE_USE_OPENSSL=ON"|' ${ENV_DIR}/cmake-3.6.3/bootstrap
  - sudo ./bootstrap
  - sudo make
  - sudo make install

  # get Android NDK R13b
  - cd ${ENV_DIR}/
  - mkdir -p ${ENV_DIR}/android-ndk
  - cd ${ENV_DIR}/android-ndk
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip android-ndk-r13b-linux-x86_64.zip

  # get SDK R25.2.3
  - cd ${ENV_DIR}/
  - mkdir -p ${ENV_DIR}/android-sdk
  - cd ${ENV_DIR}/android-sdk
  - wget https://dl.google.com/android/repository/tools_r25.2.3-linux.zip
  - unzip tools_r25.2.3-linux.zip

  # set the ENV variables
  - export ANDROID_HOME=${ENV_DIR}/android-sdk
  - export ANDROID_NDK_HOME=${ENV_DIR}/android-ndk/android-ndk-r13b
  - export ANDROID_NDK=${ANDROID_NDK_HOME}

  # Update SDK, autoconfirm license questions
  - expect -c "
    set timeout -1;
    spawn ${ENV_DIR}/android-sdk/tools/android update sdk --no-ui --all; 
    expect { "Do you accept the license" { exp_send "y\r"; exp_continue }
      eof
    }
    "

script:
  # build DualBootPatcher! (only "apk for debug release" for now)
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - cd ${TRAVIS_BUILD_DIR}/build/
  - cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug
  - make
  - rm -rf assets && cpack -G TXZ
  - make apk

  # RESULT APK: 
  - ls -l ${TRAVIS_BUILD_DIR}/build/Android_GUI/build/outputs/apk/Android_GUI-debug.apk
  - md5sum ${TRAVIS_BUILD_DIR}/build/Android_GUI/build/outputs/apk/Android_GUI-debug.apk

## [TEMPLATE] Deploy DualBootPatcher to Github Releases
# 1. Clone this repository
# 2. Copy '.travis.yml' to '.travis-original.yml' (you will need it after)
# 3. Install Travis Client <https://github.com/travis-ci/travis.rb#installation>
# 4. Run command: $(travis setup releases)
#    After follow all previous steps, pickup ONLY the "secure" line
#    and change it on '.travis-original.yml'
# 5. Move '.travis-original.yml' to '.travis.yml'
# 6. Commit it
## NOTE: You need to configure TravisCI before anything <https://travis-ci.org/>

## Deploy DualBootPatcher to Github Releases (only "apk for debug release" for now)
deploy:
  provider: releases
  skip_cleanup: true
#  api_key:
#    secure: [PUT YOUR NEW SECURE API KEY HERE]
  file_glob: true
  file:
    - "${TRAVIS_BUILD_DIR}/build/Android_GUI/build/outputs/apk/Android_GUI-debug.apk"
  on:
    branch: master
